language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - SYMFONY_VERSION=2.1.*
    - SYMFONY_VERSION=2.2.*
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*

before_script:
    - "composer self-update"
    - "composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update"
    - "composer require --dev symfony/console:${SYMFONY_VERSION} --no-update"
    - "composer require --dev symfony/finder:${SYMFONY_VERSION} --no-update"
    - "composer install --dev --no-progress --no-custom-installers --no-scripts"

script: phpunit
